### ISSUE TITLE
Limit doesn't work how it does in re.FindAllIndex

### ISSUE THREAD

**Issue by james-antill** [boyter/go-string#1]
The way you stop searching when limit is reached:

https://github.com/boyter/go-string/blob/2ecd9cca2b2d28df28fd5f4f3609f4acaee8ce53/index.go#L182

...means that you can't return the same results as re.FindAllIndex(), because it will return the first N matches and you'll return the first N matches over the first set of case permutations.

You need to search for upto limit results for each case permutation and then return the first N matches from that set of results.

**Comment by boyter** [comment]
Hah I had a feeling this would have an issue, when I refactored it way back in the day. 

I tend to use -1 most of the time so I never actually ran into this. Ill have to ensure a test is added for it.

**Comment by boyter** [comment]
Resolved with https://github.com/boyter/go-string/pull/2 and new tag v1.0.1 for you to use.

Thanks for reporting.
